stages:
  - test
  - deploy

image: python:3.12-buster
before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - mkdocs build -s
  except:
    - main

pages:
  stage: deploy
  script:
    - mkdocs build -s
    - mv site ./public
  artifacts:
    paths:
    - public
  only:
    - main